title = "Documentation"

# true: don't serve minified code in production
debug = false

# true: serve minified code in development
debug_minified = false

minified_css = "doc.min.css"
css = [
  "bootstrap.min.css",
  "bootstrap-responsive.min.css",
  "font-awesome.min.css",
  "global.css",
  "doc.css"
]

minified_js = "doc.min.js"
js = [
  "bootstrap.min.js"
]


##################
### Navigation ###
##################

[nav.new-to-tft]
title = "New to Tap for Tap?"

  [nav.new-to-tft.getting-started]
  title = "Getting Started Guide"
  url = "getting-started"

  [nav.new-to-tft.whats-new]
  title = "What's New in SDK4?"
  url = "whats-new"

  [nav.new-to-tft.download]
  title = "Download SDK4"
  url = "download"


[nav.get-users]
title = "Get Users"

  [nav.get-users.tap-exchange]
  title = "Tap Exchange"
  url = "get-users/tap-exchange"

  [nav.get-users.paid-promotion]
  title = "Paid Promotion"
  url = "get-users/paid-promotion"

  [nav.get-users.cross-promotion]
  title = "Cross Promotion"
  url = "get-users/cross-promotion"

  [nav.get-users.creative-guidelines]
  title = "Creative Guidelines"
  url = "get-users/creative-guidelines"

  [nav.get-users.geo-targeting]
  title = "Geo-Targeting"
  url = "get-users/geo-targeting"


[nav.make-money]
title = "Make Money"

  [nav.make-money.ad-overview]
  title = "Ad Overview"
  url = "make-money/ad-overview"

  [nav.make-money.reward-moment]
  title = "Reward Moment"
  url = "make-money/reward-moment"

  [nav.make-money.rescue-moment]
  title = "Rescue Moment"
  url = "make-money/rescue-moment"

  [nav.make-money.break-moment]
  title = "Break Moment"
  url = "make-money/break-moment"

  [nav.make-money.dos-donts]
  title = "Placement Do's & Don'ts"
  url = "make-money/dos-donts"

  [nav.make-money.monetization-network]
  title = "Monetization Network"
  url = "make-money/monetization-network"


[nav.android]
title = "Android"

  [nav.android.integration]
  title = "Integration Guide"
  url = "android/integration"

  [nav.android.api]
  title = "API Reference"
  url = "android/api"

  [nav.android.changelog]
  title = "SDK Changelog"
  url = "android/changelog"

# TODO: restore this when we have a 3.x to 4.x migration guide
#  [nav.android.migration]
#  title = "SDK Migration Guide"
#  url = "android/migration"

[nav.ios]
title = "iOS"

  [nav.ios.integration]
  title = "Integration Guide"
  url = "ios/integration"

  [nav.ios.api]
  title = "API Reference"
  url = "ios/api"

  [nav.ios.changelog]
  title = "SDK Changelog"
  url = "ios/changelog"

# TODO: restore this when we have a 3.x to 4.x migration guide
#  [nav.ios.migration]
#  title = "SDK Migration Guide"
#  url = "ios/migration"

[nav.unity]
title = "Unity"

    [nav.unity.integration]
    title = "Integration Guide"
    url = "unity/integration"

    [nav.unity.api]
    title = "API Reference"
    url = "unity/api"

    [nav.unity.changelog]
    title = "SDK Changelog"
    url = "unity/changelog"

[nav.help]
title = "More Help"

# TODO: new integration videos?
#  [nav.help.videos]
#  title = "Instructional Videos"
#  url = "help/videos"

  [nav.help.glossary]
  title = "Glossary"
  url = "help/glossary"

  [nav.help.support]
  title = "Support"
  url = "help/support"
